apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-cluster-admin
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: demo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      serviceAccountName: app-sa
      containers:
        - name: main
          image: nginx:latest
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: host-docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
